name = "quantumclubgceksite"
main = "index.js"
compatibility_date = "2026-04-14"

[assets]
directory = "./"
binding = "ASSETS"

[vars]
# Add your GitHub Client ID here
GITHUB_CLIENT_ID = "Ov23lixI9kGDvUP0XccC"

#123
