name = "quantumclubgceksite"
main = "index.js"
compatibility_date = "2026-04-14"

[assets]
directory = "./"
binding = "assets"

[vars]
# You can put non-sensitive variables here, 
# but GITHUB_CLIENT_SECRET must be added in the Cloudflare Dashboard UI.
