name = "quantumclubgceksite"
main = "index.js"
compatibility_date = "2026-04-14"

[assets]
directory = "./"
binding = "ASSETS"

[vars]
# Add your GitHub Client ID here
GITHUB_CLIENT_ID = "Ov23lixI9kGDvUP0XccC"
GITHUB_CLIENT_SECRET = "522a5e97ef38b9bd3bd723062f30b3b5114eceda" 
GITHUB_TOKEN = "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"
